# Generated by Django 3.0.9 on 2020-09-05 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 31, 15, 130462, tzinfo=utc))),
                ('safe', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message')),
                ('replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Reply')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Tweet')),
            ],
        ),
    ]
