# Generated by Django 3.0.9 on 2020-09-05 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 18, 45, 54, 65574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Tweet'),
        ),
    ]
