# Generated by Django 3.0.8 on 2020-09-07 21:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0004_auto_20200906_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 21, 20, 7, 928013, tzinfo=utc)),
        ),
    ]
