# Generated by Django 3.0.8 on 2020-09-07 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0010_auto_20200907_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 22, 24, 48, 470207, tzinfo=utc)),
        ),
    ]
