# Generated by Django 3.0.8 on 2020-09-08 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0012_auto_20200907_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 13, 18, 27, 209868, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message')),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Tweet')),
            ],
        ),
    ]
