# Generated by Django 3.0.8 on 2020-09-08 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0014_auto_20200908_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 13, 34, 2, 154656, tzinfo=utc)),
        ),
    ]
