# Generated by Django 3.0.8 on 2020-09-08 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0017_auto_20200908_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 13, 40, 40, 85260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_set', to='tweetapp.Tweet'),
        ),
    ]
