# Generated by Django 3.0.8 on 2020-09-08 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0020_auto_20200908_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 16, 2, 26, 835441, tzinfo=utc)),
        ),
    ]
