# Generated by Django 3.0.8 on 2020-09-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0023_auto_20200908_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replies',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='tweetapp.Reply'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='was_retweeted',
            field=models.BooleanField(default=False),
        ),
    ]
