# Generated by Django 3.0.8 on 2020-09-09 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0024_auto_20200909_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='retweet',
            new_name='tweet',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date_created',
        ),
        migrations.AddField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
