# Generated by Django 3.0.8 on 2020-09-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0025_auto_20200909_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='message',
            name='retweets',
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_set', to='tweetapp.Reply'),
        ),
    ]
