# Generated by Django 3.0.8 on 2020-09-09 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0026_auto_20200909_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='date_created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
