# Generated by Django 3.0.8 on 2020-09-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0028_auto_20200910_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message'),
        ),
    ]
