# Generated by Django 3.0.8 on 2020-09-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0029_auto_20200910_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='fk',
        ),
        migrations.AddField(
            model_name='feed',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Feed'),
        ),
        migrations.AddField(
            model_name='rep',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Rep'),
        ),
    ]
