# Generated by Django 3.0.8 on 2020-09-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0030_auto_20200910_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_set', to='tweetapp.Rep'),
        ),
    ]
