# Generated by Django 3.0.8 on 2020-09-10 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0031_rep_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_set', to='tweetapp.Feed'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_set', to='tweetapp.Rep'),
        ),
    ]
