# Generated by Django 3.0.8 on 2020-09-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0032_auto_20200910_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='tweet',
        ),
        migrations.AddField(
            model_name='feed',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_set', to='tweetapp.Feed'),
        ),
        migrations.AddField(
            model_name='rep',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_set', to='tweetapp.Feed'),
        ),
    ]
