# Generated by Django 3.0.9 on 2020-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0035_auto_20200910_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/tweetapp/%Y%M/'),
        ),
    ]
