# Generated by Django 3.0.9 on 2020-09-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0036_message_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='media',
            new_name='image',
        ),
    ]
