# Generated by Django 3.0.9 on 2020-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0037_auto_20200911_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweetapp/messages/%Y%M/'),
        ),
    ]
