# Generated by Django 3.0.9 on 2020-09-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0040_auto_20200911_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mention',
        ),
    ]
