# Generated by Django 3.0.9 on 2020-09-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0041_delete_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
    ]
