# Generated by Django 3.0.9 on 2020-10-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0043_auto_20201001_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text-content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='image-content',
            new_name='image',
        ),
    ]
