# Generated by Django 3.0.9 on 2020-10-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0046_auto_20201004_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationinvite',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
