# Generated by Django 3.0.9 on 2020-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0048_auto_20201009_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
