# Generated by Django 3.0.9 on 2020-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0050_conversation_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='seen',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='profile_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
