# Generated by Django 3.0.9 on 2020-10-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0051_auto_20201011_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
