# Generated by Django 3.0.9 on 2020-10-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0053_auto_20201012_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message'),
        ),
    ]
