# Generated by Django 3.0.8 on 2020-09-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200907_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifier',
            name='notifications',
            field=models.ManyToManyField(to='userapp.Notification'),
        ),
    ]
