# Generated by Django 3.0.8 on 2020-09-08 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0021_auto_20200908_1602'),
        ('userapp', '0007_notifier_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 16, 2, 26, 875595, tzinfo=utc))),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 16, 2, 26, 879744, tzinfo=utc))),
                ('reply', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Reply')),
                ('tweet', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Tweet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.Profile')),
            ],
        ),
    ]
