# Generated by Django 3.0.8 on 2020-09-08 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20200908_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
