# Generated by Django 3.0.8 on 2020-09-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_auto_20200908_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifier',
            name='content',
        ),
    ]
