# Generated by Django 3.0.9 on 2020-09-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_auto_20200910_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='url',
            new_name='link',
        ),
    ]
