# Generated by Django 3.0.9 on 2020-09-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0037_auto_20200911_1501'),
        ('userapp', '0018_auto_20200911_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Message'),
        ),
    ]
