# Generated by Django 3.0.9 on 2020-09-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_auto_20200911_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='profile',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='profile',
            new_name='creator',
        ),
    ]
