# Generated by Django 3.0.9 on 2020-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_thrend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='userapp/profile-covers/default.png', null=True, upload_to='userapp/profile-covers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='userapp/profile-pictures/default.png', null=True, upload_to='userapp/profile-pictures/'),
        ),
    ]
