# Generated by Django 3.0.9 on 2020-10-03 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0044_auto_20201001_2228'),
        ('userapp', '0024_auto_20201003_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='follow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_notification', to='userapp.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.Like'),
        ),
        migrations.AddField(
            model_name='notification',
            name='mention',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.Mention'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Reply'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tweet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Tweet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
