# Generated by Django 3.0.9 on 2020-10-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_auto_20201003_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tweet',
        ),
    ]
